# Kappa Kernel Travis-CI

language:
    - c

install:
    # Install linaro 4.7 android toolchain
    - wget http://releases.linaro.org/14.01/components/android/toolchain/4.7/android-toolchain-eabi-4.7-2014.01-x86.tar.bz2 -O linaro.tar.bz2
    - tar -xvjf linaro.tar.bz2
    # -- end
    # Prepare kappa.config file
    - echo "KAPPA_HOME=$PWD" > "$PWD/kappa.config"
    - echo "KAPPA_COMPILER="$PWD/android-toolchain-eabi/bin/arm-eabi-" >> "$PWD/kappa.config"
    - export PATH="$PWD/tools":$PATH
    - cd $HOME/Kappa
    # -- end

script:
    # Build it all
    - mkall
